server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false

  application:
    name: FEEMS

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:feedb      #     url: jdbc:h2:file:../ms-assignments/data/feedb
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#  instance:
#    hostname: localhost

