create table FEEDB.PUBLIC.FEE (
    ID     integer generated by default as identity (exhausted),
    SID    VARCHAR2(30)                 not null,
    AMOUNT DECIMAL(8, 2) default 0.00   not null,
    STATUS VARCHAR2(30)  default 'NONE' not null,
    constraint "FEE_pk"
        primary key (ID)
);

insert into FEEDB.PUBLIC.FEE (id,SID, AMOUNT,STATUS) values (1,'09990', 123.78,'NONE');
insert into FEEDB.PUBLIC.FEE (id,SID, AMOUNT,STATUS) values (2,'09900', 1213.78,'NONE');
insert into FEEDB.PUBLIC.FEE (id,SID, AMOUNT,STATUS) values (3,'09930', 1237.78,'NONE');

select * from FEEDB.PUBLIC.FEE;